export const symptomDataset = [
  ['headache', ['head pain', 'migraine'], 'Neurologist', false],
  ['fever', ['high temperature', 'temperature'], 'General Physician', false],
  ['cough', ['dry cough', 'wet cough'], 'Pulmonologist', false],
  ['chest pain', ['heart pain', 'tight chest'], 'Emergency Medicine', true],
  ['breathing difficulty', ['shortness of breath', 'cannot breathe'], 'Emergency Medicine', true],
  ['unconsciousness', ['fainted', 'passed out'], 'Emergency Medicine', true],
  ['abdominal pain', ['stomach pain', 'belly pain'], 'Gastroenterologist', false],
  ['vomiting', ['throwing up', 'nausea'], 'General Physician', false],
  ['diarrhea', ['loose motion', 'watery stool'], 'Gastroenterologist', false],
  ['rash', ['skin allergy', 'red spots'], 'Dermatologist', false],
  ['back pain', ['lower back pain', 'spine pain'], 'Orthopedist', false],
  ['joint pain', ['knee pain', 'elbow pain'], 'Orthopedist', false],
  ['dizziness', ['lightheaded', 'vertigo'], 'ENT Specialist', false],
  ['sore throat', ['throat pain', 'scratchy throat'], 'ENT Specialist', false],
  ['ear pain', ['earache'], 'ENT Specialist', false],
  ['eye redness', ['red eye', 'eye irritation'], 'Ophthalmologist', false],
  ['blurred vision', ['vision problem'], 'Ophthalmologist', false],
  ['tooth pain', ['toothache'], 'Dentist', false],
  ['anxiety', ['panic', 'nervousness'], 'Psychiatrist', false],
  ['depression', ['low mood', 'hopeless'], 'Psychiatrist', false],
  ['insomnia', ['cannot sleep', 'sleep problem'], 'Psychiatrist', false],
  ['fatigue', ['tiredness', 'weakness'], 'General Physician', false],
  ['weight loss', ['losing weight'], 'General Physician', false],
  ['weight gain', ['gaining weight'], 'Endocrinologist', false],
  ['high sugar', ['diabetes', 'blood sugar'], 'Endocrinologist', false],
  ['thyroid swelling', ['neck swelling'], 'Endocrinologist', false],
  ['palpitations', ['fast heartbeat'], 'Cardiologist', false],
  ['high blood pressure', ['hypertension'], 'Cardiologist', false],
  ['leg swelling', ['swollen feet'], 'Cardiologist', false],
  ['burning urination', ['urine burning'], 'Urologist', false],
  ['frequent urination', ['pee often'], 'Urologist', false],
  ['pregnancy concern', ['missed period'], 'Gynecologist', false],
  ['period pain', ['menstrual cramps'], 'Gynecologist', false],
  ['acne', ['pimples'], 'Dermatologist', false],
  ['hair fall', ['hair loss'], 'Dermatologist', false],
  ['wound', ['cut injury'], 'General Surgeon', false],
  ['fracture', ['broken bone'], 'Orthopedist', false],
  ['burn', ['skin burn'], 'Emergency Medicine', false],
  ['nose bleed', ['bleeding nose'], 'ENT Specialist', false],
  ['seizure', ['fits', 'convulsion'], 'Emergency Medicine', true],
  ['stroke symptoms', ['face droop', 'arm weakness'], 'Emergency Medicine', true],
  ['allergy', ['hives', 'itching'], 'Allergist', false],
  ['swollen throat', ['throat closing'], 'Emergency Medicine', true],
  ['covid symptoms', ['loss of smell'], 'General Physician', false],
  ['constipation', ['hard stool'], 'Gastroenterologist', false],
  ['jaundice', ['yellow eyes'], 'Gastroenterologist', false],
  ['blood in stool', ['rectal bleeding'], 'Gastroenterologist', false],
  ['memory loss', ['forgetfulness'], 'Neurologist', false],
  ['tremor', ['shaking hands'], 'Neurologist', false],
  ['child fever', ['baby fever'], 'Pediatrician', false],
  ['infant crying', ['baby crying'], 'Pediatrician', false],
  ['dehydration', ['very thirsty'], 'Emergency Medicine', false]
].map(([symptom, synonyms, doctor, emergency]) => ({
  symptom,
  synonyms,
  recommendedDoctor: doctor,
  emergencyFlag: emergency,
  followUpQuestions: ['How long has this been happening?', 'How severe is it from 1 to 10?', 'Do you have any related symptoms?'],
  severityRules: ['Seek urgent care if symptoms are severe, sudden, worsening, or associated with fainting, chest pain, or breathing trouble.'],
  safeRemedies: ['Rest, hydrate, and monitor symptoms. Book a doctor consultation for persistent or worsening symptoms.']
}));
